// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddCategory(arg1:string,arg2:string):Promise<void>;

export function AddCustomField(arg1:string,arg2:string):Promise<void>;

export function AddInvoice(arg1:backend.Invoice):Promise<number>;

export function AddVendor(arg1:backend.Vendor):Promise<void>;

export function CheckUnpaidInvoices():Promise<void>;

export function ClearAllInvoices():Promise<void>;

export function DeleteCategory(arg1:string,arg2:string):Promise<void>;

export function DeleteChartConfig(arg1:number):Promise<void>;

export function DeleteCustomField(arg1:string):Promise<void>;

export function DeleteInvoice(arg1:number):Promise<void>;

export function DeleteVendor(arg1:number):Promise<void>;

export function GetAllInvoices():Promise<Array<backend.Invoice>>;

export function GetCategories(arg1:string):Promise<Array<string>>;

export function GetChartConfigs():Promise<Array<backend.ChartConfig>>;

export function GetCustomFields():Promise<Record<string, string>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetVendors():Promise<Array<backend.Vendor>>;

export function MarkAsPaid(arg1:number,arg2:boolean):Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function RenameCategory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveChartConfig(arg1:backend.ChartConfig):Promise<void>;

export function UpdateInvoice(arg1:backend.Invoice):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string):Promise<void>;
